sudo: required
services:
  - docker
  
before_install:
  - docker build -t dockerluffy/react-dev:latest -f Dockerfile.dev .

script:
  - docker run dockerluffy/react-dev npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-782474979332"
  app: "DockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
